services:
  - type: web
    name: agrolink
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Agrolink.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "agrolink.onrender.com"
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_WEBHOOK_SECRET
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false 