# Generated by Django 5.2 on 2025-05-31 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
    ]
