# Generated by Django 5.2 on 2025-05-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_auto_20250531_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('grains', 'Grains'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('poultry', 'Poultry'), ('seafood', 'Seafood'), ('herbs', 'Herbs'), ('spices', 'Spices'), ('other', 'Other')], max_length=20),
        ),
    ]
